splash = 0

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers
    fit_mode = cover
    timeout = 600
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers
    fit_mode = cover
    timeout = 100
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers
    fit_mode = cover
    timeout = 100
}
